BC-3056 - Pass max file size to dropzone
schul-cloud/schulcloud-client pull request #3086
Opened 2023-01-26 15:03 UTC by bischofmax

# Description

## Links to Tickets or other pull requests

## Changes

## Data Security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-01-30 12:34 UTC, dyedwiper commented on static/scripts/files-storage.js
> -				dictFileTooBig: errorMessages.FILE_TO_BIG,
errorMessages.FILE_TO_BIG wird dann auch gar nicht mehr benutzt und du kannst die Definition entfernen.

2023-01-30 12:35 UTC, dyedwiper commented on static/scripts/files-storage.js
> +			const fileTooBigError = $t('global.text.fileTooLarge', { maxFileSizeInGb });
`fileTooLargeError` wär in Übereinstimmung mit dem Namen der Texte.

2023-01-30 13:20 UTC, dyedwiper approved these changes

2023-02-01 09:41 UTC, CeEv requested changes

2023-02-01 09:41 UTC, CeEv commented on static/scripts/files-storage.js
> +			const maxFileSizeInGb = String(Number(maxFilesize) / 1000);
Das ist MB in GB? Dann müssten es /1024 sein.

2023-02-01 09:41 UTC, CeEv commented on static/scripts/files-storage.js
> +				dictFileTooBig: fileTooBigError,
Macht es Sinn, dictFileTooBig in fileTooBigError umzubenennen?

2023-02-01 09:41 UTC, CeEv commented on static/scripts/files.js
> +		const maxFileSizeInGb = String(Number(maxFilesize) / 1000);
Umrechnung 1024

2023-02-01 09:56 UTC, dyedwiper commented on static/scripts/files.js
> +		const dictFileTooBig = $t('global.text.fileTooLarge', { maxFileSizeInGb });
Im files-storage hast du die Konstante fileTooBigError genannt. Damit es einheitlich ist, würd ich sie hier auch so nennen.

2023-02-01 14:10 UTC, CeEv approved these changes

2023-02-02 09:22 UTC, merged